/*********************************************************************
** Program Name: Euler2 - Even Fibonacci numbers
** Problem URL: https://projecteuler.net/problem=2
** Solution Author: Charles Joshua Ledbetter
** Date Solved: 7/19/2018

** Description:
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
*********************************************************************/
#include<iostream>

#define SIZE 4000000

using std::cout;
using std::endl;

int main(){
  // variables for calculating solution
  int sum = 0;
  int last = 0;
  int current = 1;
  int temp = 0;

  // sum Fibonacci numbers until SIZE is reached
  while(1){
    temp = last + current;
    last = current;
    current = temp;
    if(current > SIZE){
      break;
    }
    else if(current % 2 == 0){
      sum += current;
    }
  }

  // print solution
  cout << sum << endl;

  return 1;
}
